GMAIL_USERNAME: "restorani.ba@gmail.com"
GMAIL_PASSWORD: "tastatura11"
RECAPTCHA_PUBLIC_KEY: "6Lfug_ISAAAAAP_W63AO4vfQLhc0UyOgC2Lk2xo2"
RECAPTCHA_PRIVATE_KEY: "6Lfug_ISAAAAAFOfEEAdf4Dx41_ve7b3FVWGZc9g"
POSTGRES_USERNAME: "postgres"
POSTGRES_PASSWORD: "postgres"
POSTGRES_HEROKU_USERNAME: "venjiugfxtdlcp"
POSTGRES_HEROKU_PASSWORD: "1ZJATmax280KWqv8Xu4QToiIXs"